# usage:
# make clobber
# make

all: \
art_gallery_cam01.lxs \
art_gallery_cam02.lxs \
art_gallery_cam03.lxs \
art_gallery_cam04.lxs \
art_gallery_cam05.lxs \
art_gallery_cam06.lxs

clean:
	-rm -f *~ art_gallery_*.lxs

clobber: clean
	-rm -f luxout.png

# art_gallery_cam01

art_gallery_cam01.lxs: art_gallery_cam01.patch
	patch art_gallery.lxs -i art_gallery_cam01.patch -o art_gallery_cam01.lxs
	@echo "render (on Linux) with: luxrender art_gallery_cam01.lxs"
	@echo "or"
	@echo "(on Mac OS X) with: open art_gallery_cam01.lxs"
	@echo "open INI file from there (via 'File -> Load Panel Settings...')"

# art_gallery_cam02

art_gallery_cam02.lxs: art_gallery_cam02.patch
	patch art_gallery.lxs -i art_gallery_cam02.patch -o art_gallery_cam02.lxs
	@echo "render (on Linux) with: luxrender art_gallery_cam02.lxs"
	@echo "or"
	@echo "(on Mac OS X) with: open art_gallery_cam02.lxs"
	@echo "open INI file from there (via 'File -> Load Panel Settings...')"

# art_gallery_cam03

art_gallery_cam03.lxs: art_gallery_cam03.patch
	patch art_gallery.lxs -i art_gallery_cam03.patch -o art_gallery_cam03.lxs
	@echo "render (on Linux) with: luxrender art_gallery_cam03.lxs"
	@echo "or"
	@echo "(on Mac OS X) with: open art_gallery_cam03.lxs"
	@echo "open INI file from there (via 'File -> Load Panel Settings...')"

# art_gallery_cam04

art_gallery_cam04.lxs: art_gallery_cam04.patch
	patch art_gallery.lxs -i art_gallery_cam04.patch -o art_gallery_cam04.lxs
	@echo "render (on Linux) with: luxrender art_gallery_cam04.lxs"
	@echo "or"
	@echo "(on Mac OS X) with: open art_gallery_cam04.lxs"
	@echo "open INI file from there (via 'File -> Load Panel Settings...')"

# art_gallery_cam05

art_gallery_cam05.lxs: art_gallery_cam05.patch
	patch art_gallery.lxs -i art_gallery_cam05.patch -o art_gallery_cam05.lxs
	@echo "render (on Linux) with: luxrender art_gallery_cam05.lxs"
	@echo "or"
	@echo "(on Mac OS X) with: open art_gallery_cam05.lxs"
	@echo "open INI file from there (via 'File -> Load Panel Settings...')"

# art_gallery_cam06

art_gallery_cam06.lxs: art_gallery_cam06.patch
	patch art_gallery.lxs -i art_gallery_cam06.patch -o art_gallery_cam06.lxs
	@echo "render (on Linux) with: luxrender art_gallery_cam06.lxs"
	@echo "or"
	@echo "(on Mac OS X) with: open art_gallery_cam06.lxs"
	@echo "open INI file from there (via 'File -> Load Panel Settings...')"

